site_name: DISK
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js

repo_url: https://github.com/KnowledgeCaptureAndDiscovery/DISK-UI
edit_uri: edit/main/docs/
nav:
  - Overview: index.md
  - Concepts: concepts.md
 # - Getting Started: getting-started.md
  - User Guide: 
    - user-guide/index.md
    - user-guide/write-hypothesis.md
    - user-guide/test-hypothesis.md
  - Advanced User Guide: 
    - advanced-user-guide/index.md
    - advanced-user-guide/steps/add-basic-info.md
    - advanced-user-guide/steps/write-query.md
  - Administrator Guide:
    - admin-guide/index.md
    - Add questions:
      - admin-guide/questions/overview.md 
      - admin-guide/questions/disk-ontologies.md
      - admin-guide/questions/question-ontology.md
      - admin-guide/questions/extending-ontology.md
    - Add workflows:
      - admin-guide/running-workflows.md
  - Developer Guide: 
    - developer-guide/index.md
    - developer-guide/architecture.md
    - developer-guide/data-adapter.md
    - developer-guide/method-adapter.md
    - developer-guide/installation.md 
    - developer-guide/configuration.md
  - Adoptions: adoptions.md
  - Ontologies: ontologies.md
theme:
  name: material
  logo: figures/logo.png
  favicon: figures/favicon.ico
  palette:
    primary: teal


markdown_extensions:
- codehilite
- admonition
- toc:
    toc_depth : "1-1"
    permalink: true
