site_name: DISK
extra_css:
- assets/versions.css
- assets/extra.css
extra_javascript:
- assets/versions.js

nav:
  - Overview: index.md
  - Concepts: concepts.md
  - Getting Started: getting-started.md
  - User Guide: 
    - user-guide/index.md
    - user-guide/write-hypothesis.md
    - user-guide/test-hypothesis.md
  - Operator Manual: 
    - operator-manual/index.md
    - Data Extraction:
      - Overview: user-guide/data-extraction.md
      - SPARQL: user-guide/data-extraction-sparql.md
    - Running Workflows: user-guide/running-workflows.md
  - Developer Guide: 
    - developer-guide/index.md
  - FAQ: faq.md
theme:
  name: material
  logo: figures/logo.png
  favicon: figures/favicon.ico
  palette:
    primary: teal


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - mkdocs-video